on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
      #- 'mona/octocat'
      #- 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:        
      - INT
      - E2EM
      - B2B
      - APIGW
      - APIP
      - SAG CLOUD
      
